package net.enelson.sopemojis.pack;

import net.enelson.sopemojis.model.EmojiDefinition;
import org.bukkit.configuration.file.FileConfiguration;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Node;

import javax.imageio.ImageIO;
import javax.imageio.ImageReader;
import javax.imageio.metadata.IIOMetadata;
import javax.imageio.stream.ImageInputStream;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.BufferedOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public final class ResourcePackGenerator {

    private static final Logger LOGGER = Logger.getLogger(ResourcePackGenerator.class.getName());

    public Path generate(Path pluginDataFolder, FileConfiguration config, List<EmojiDefinition> emojis) throws IOException {
        Path workDir = pluginDataFolder.resolve("generated/workpack");
        Path output = pluginDataFolder.resolve(config.getString("pack.output-file", "generated/sopemojis-pack.zip"));
        Path sourceDir = pluginDataFolder.resolve("emoji-textures");

        Path minecraftRoot = workDir.resolve("assets/minecraft");
        Path texturesDir = minecraftRoot.resolve("textures/font/emoji");
        Path fontDir = minecraftRoot.resolve("font");
        Path atlasDir = minecraftRoot.resolve("atlases");

        cleanDirectory(workDir);
        Files.createDirectories(texturesDir);
        Files.createDirectories(fontDir);
        Files.createDirectories(atlasDir);
        if (output.getParent() != null) {
            Files.createDirectories(output.getParent());
        }

        String description = escapeJson(config.getString("pack.description", "Generated by SopEmojis"));
        int packFormat = config.getInt("pack.pack-format", 6);

        writeString(workDir.resolve("pack.mcmeta"),
                "{\n" +
                        "  \"pack\": {\n" +
                        "    \"pack_format\": " + packFormat + ",\n" +
                        "    \"description\": \"" + description + "\"\n" +
                        "  }\n" +
                        "}\n");

        writeString(fontDir.resolve("default.json"), buildFontJson(emojis));
        writeString(atlasDir.resolve("blocks.json"), buildBlocksAtlasJson());

        int processed = 0;
        for (EmojiDefinition emoji : emojis) {
            if (!emoji.isEnabled()) {
                continue;
            }

            Path source = sourceDir.resolve(emoji.getTextureFile());
            if (!Files.exists(source)) {
                throw new IOException("Missing texture: " + source);
            }

            processTexture(sourceDir, texturesDir, emoji);
            processed++;
        }

        zipDirectory(workDir, output);
        LOGGER.info("SopEmojis resource pack generated: " + output + " (processed emojis: " + processed + ")");
        return output;
    }

    private void processTexture(Path sourceDir, Path texturesDir, EmojiDefinition emoji) throws IOException {
        Path source = sourceDir.resolve(emoji.getTextureFile());

        if (isGif(source)) {
            String pngName = toPngFileName(emoji.getTextureFile());
            Path targetPng = texturesDir.resolve(pngName);
            convertGifToAnimatedPng(source, targetPng);
            return;
        }

        Path target = texturesDir.resolve(emoji.getTextureFile());
        Files.copy(source, target, StandardCopyOption.REPLACE_EXISTING);

        Path metaSource = sourceDir.resolve(emoji.getTextureFile() + ".mcmeta");
        if (Files.exists(metaSource)) {
            Path metaTarget = texturesDir.resolve(emoji.getTextureFile() + ".mcmeta");
            Files.copy(metaSource, metaTarget, StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private String buildFontJson(List<EmojiDefinition> emojis) {
        List<String> providers = new ArrayList<String>();
        for (EmojiDefinition emoji : emojis) {
            if (!emoji.isEnabled() || !emoji.isFont()) {
                continue;
            }
            providers.add("    {\n"
                    + "      \"type\": \"bitmap\",\n"
                    + "      \"file\": \"minecraft:font/emoji/" + escapeJson(stripImageExtension(emoji.getTextureFile())) + ".png\",\n"
                    + "      \"ascent\": " + emoji.getAscent() + ",\n"
                    + "      \"height\": " + emoji.getHeight() + ",\n"
                    + "      \"chars\": [\"" + escapeJson(emoji.getUnicodeChar()) + "\"]\n"
                    + "    }");
        }

        StringBuilder builder = new StringBuilder();
        builder.append("{\n  \"providers\": [\n");
        for (int i = 0; i < providers.size(); i++) {
            if (i > 0) {
                builder.append(",\n");
            }
            builder.append(providers.get(i));
        }
        builder.append("\n  ]\n}\n");
        return builder.toString();
    }

    private String buildBlocksAtlasJson() {
        return "{\n" +
                "  \"sources\": [\n" +
                "    {\n" +
                "      \"type\": \"directory\",\n" +
                "      \"source\": \"font/emoji\",\n" +
                "      \"prefix\": \"emoji/\"\n" +
                "    }\n" +
                "  ]\n" +
                "}\n";
    }

    private boolean isGif(Path file) {
        String name = file.getFileName().toString().toLowerCase();
        return name.endsWith(".gif");
    }

    private String toPngFileName(String file) {
        return stripImageExtension(file) + ".png";
    }

    private String stripImageExtension(String file) {
        String lower = file.toLowerCase();
        if (lower.endsWith(".png") || lower.endsWith(".gif")) {
            return file.substring(0, file.length() - 4);
        }
        return file;
    }

    private void convertGifToAnimatedPng(Path gifSource, Path pngTarget) throws IOException {
        List<BufferedImage> frames = new ArrayList<BufferedImage>();
        List<Integer> frameTimes = new ArrayList<Integer>();

        ImageInputStream input = null;
        try {
            input = ImageIO.createImageInputStream(Files.newInputStream(gifSource));
            Iterator<ImageReader> readers = ImageIO.getImageReadersByFormatName("gif");
            if (!readers.hasNext()) {
                throw new IOException("GIF reader not available for file: " + gifSource);
            }

            ImageReader reader = readers.next();
            try {
                reader.setInput(input, false);

                int numFrames = reader.getNumImages(true);
                if (numFrames <= 0) {
                    throw new IOException("GIF has no frames: " + gifSource);
                }

                for (int i = 0; i < numFrames; i++) {
                    BufferedImage frame = reader.read(i);
                    frames.add(ensureArgb(frame));

                    int delayMs = readGifDelayMs(reader.getImageMetadata(i));
                    int mcTicks = Math.max(1, Math.round(delayMs / 50.0f));
                    frameTimes.add(mcTicks);
                }
            } finally {
                reader.dispose();
            }
        } finally {
            if (input != null) {
                input.close();
            }
        }

        int width = 0;
        int height = 0;
        for (BufferedImage frame : frames) {
            width = Math.max(width, frame.getWidth());
            height = Math.max(height, frame.getHeight());
        }
        if (width <= 0 || height <= 0) {
            throw new IOException("Unable to determine GIF dimensions for " + gifSource);
        }

        BufferedImage spriteSheet = new BufferedImage(width, height * frames.size(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = spriteSheet.createGraphics();
        try {
            for (int i = 0; i < frames.size(); i++) {
                graphics.drawImage(frames.get(i), 0, i * height, null);
            }
        } finally {
            graphics.dispose();
        }

        if (pngTarget.getParent() != null) {
            Files.createDirectories(pngTarget.getParent());
        }
        ImageIO.write(spriteSheet, "png", pngTarget.toFile());

        Path mcmetaPath = Paths.get(pngTarget.toString() + ".mcmeta");
        writeString(mcmetaPath, buildAnimationMcmeta(frameTimes));
    }

    private BufferedImage ensureArgb(BufferedImage image) {
        if (image.getType() == BufferedImage.TYPE_INT_ARGB) {
            return image;
        }

        BufferedImage converted = new BufferedImage(image.getWidth(), image.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = converted.createGraphics();
        try {
            graphics.drawImage(image, 0, 0, null);
        } finally {
            graphics.dispose();
        }
        return converted;
    }

    private int readGifDelayMs(IIOMetadata metadata) {
        if (metadata == null) {
            return 50;
        }

        String format = metadata.getNativeMetadataFormatName();
        if (format == null) {
            return 50;
        }

        Node root = metadata.getAsTree(format);
        Node node = findNode(root, "GraphicControlExtension");
        if (node == null) {
            return 50;
        }

        NamedNodeMap attributes = node.getAttributes();
        if (attributes == null) {
            return 50;
        }

        Node delayNode = attributes.getNamedItem("delayTime");
        if (delayNode == null) {
            return 50;
        }

        try {
            int hundredths = Integer.parseInt(delayNode.getNodeValue());
            return Math.max(10, hundredths * 10);
        } catch (NumberFormatException ignored) {
            return 50;
        }
    }

    private Node findNode(Node root, String name) {
        if (root == null) {
            return null;
        }
        if (name.equals(root.getNodeName())) {
            return root;
        }

        Node child = root.getFirstChild();
        while (child != null) {
            Node found = findNode(child, name);
            if (found != null) {
                return found;
            }
            child = child.getNextSibling();
        }
        return null;
    }

    private String buildAnimationMcmeta(List<Integer> frameTimes) {
        StringBuilder framesBuilder = new StringBuilder();
        for (int i = 0; i < frameTimes.size(); i++) {
            if (i > 0) {
                framesBuilder.append(",\n");
            }
            framesBuilder.append("      { \"index\": ").append(i).append(", \"time\": ").append(frameTimes.get(i)).append(" }");
        }

        return "{\n" +
                "  \"animation\": {\n" +
                "    \"interpolate\": false,\n" +
                "    \"frames\": [\n" +
                framesBuilder.toString() + "\n" +
                "    ]\n" +
                "  }\n" +
                "}\n";
    }

    private void cleanDirectory(Path directory) throws IOException {
        if (!Files.exists(directory)) {
            return;
        }

        List<Path> paths = new ArrayList<Path>();
        java.nio.file.FileVisitor<Path> visitor = new java.nio.file.SimpleFileVisitor<Path>() {
            @Override
            public java.nio.file.FileVisitResult visitFile(Path file, java.nio.file.attribute.BasicFileAttributes attrs) throws IOException {
                paths.add(file);
                return java.nio.file.FileVisitResult.CONTINUE;
            }

            @Override
            public java.nio.file.FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
                paths.add(dir);
                return java.nio.file.FileVisitResult.CONTINUE;
            }
        };
        Files.walkFileTree(directory, visitor);
        Collections.sort(paths, new Comparator<Path>() {
            @Override
            public int compare(Path first, Path second) {
                return Integer.compare(second.getNameCount(), first.getNameCount());
            }
        });
        for (Path path : paths) {
            if (!path.equals(directory)) {
                Files.deleteIfExists(path);
            }
        }
    }

    private void zipDirectory(Path sourceDir, Path outputZip) throws IOException {
        Files.deleteIfExists(outputZip);

        List<Path> files = new ArrayList<Path>();
        java.nio.file.FileVisitor<Path> visitor = new java.nio.file.SimpleFileVisitor<Path>() {
            @Override
            public java.nio.file.FileVisitResult visitFile(Path file, java.nio.file.attribute.BasicFileAttributes attrs) throws IOException {
                files.add(file);
                return java.nio.file.FileVisitResult.CONTINUE;
            }
        };
        Files.walkFileTree(sourceDir, visitor);

        OutputStream fileOut = null;
        ZipOutputStream zipOut = null;
        try {
            fileOut = Files.newOutputStream(outputZip, StandardOpenOption.CREATE_NEW);
            zipOut = new ZipOutputStream(new BufferedOutputStream(fileOut), StandardCharsets.UTF_8);
            for (Path path : files) {
                String entryName = sourceDir.relativize(path).toString().replace('\\', '/');
                zipOut.putNextEntry(new ZipEntry(entryName));
                Files.copy(path, zipOut);
                zipOut.closeEntry();
            }
        } finally {
            if (zipOut != null) {
                zipOut.close();
            } else if (fileOut != null) {
                fileOut.close();
            }
        }
    }

    private void writeString(Path file, String content) throws IOException {
        if (file.getParent() != null) {
            Files.createDirectories(file.getParent());
        }
        Files.write(file, content.getBytes(StandardCharsets.UTF_8), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
    }

    private String escapeJson(String input) {
        return input.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}